### ISSUE TITLE
add command validation to task queue code

### ISSUE THREAD

**Issue by jgpawletko** [rrasch/task-queue#3]
I found (by accident) that this invocation kills all of the task-queue worker processes on a worker host that received the message:
```
echo "$DIRS" | xargs add-mb-job -m "$MB_HOST" \
 -r /<some-path>/${PARTNER}/${COLLECTION} \
-s book_publisher:
```
The `task-queue` code could check that the argument to `-s` was valid and, if not, return an error.

**Comment by rrasch** [comment]
I've added validation in commit 180d0cc2b9fd5fc0e38e401fb4d708abb8d1f911
